name: Keep Render Apps Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # her 10 dakikada bir
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Ping FastAPI /docs (Swagger)
        run: |
          curl -L --retry 2 --max-time 15 --fail \
            https://email-automation-ko-project.onrender.com/docs

      - name: Ping n8n (root)
        run: |
          # n8n bazen 302/401 dönebiliyor; hata kodunu yoksaymak için || true
          curl -L --retry 2 --max-time 15 \
            https://email-automation-n8n.onrender.com/ || true
